from typing import Any, Optional
from wagtail.admin.forms.choosers import AnchorLinkChooserForm as AnchorLinkChooserForm, EmailLinkChooserForm as EmailLinkChooserForm, ExternalLinkChooserForm as ExternalLinkChooserForm, PhoneLinkChooserForm as PhoneLinkChooserForm
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.admin.modal_workflow import render_modal_workflow as render_modal_workflow
from wagtail.core import hooks as hooks
from wagtail.core.models import Page as Page, UserPagePermissionsProxy as UserPagePermissionsProxy
from wagtail.core.utils import resolve_model_string as resolve_model_string

def shared_context(request: Any, extra_context: Optional[Any] = ...): ...
def page_models_from_string(string: Any): ...
def filter_page_type(queryset: Any, page_models: Any): ...
def can_choose_page(page: Any, permission_proxy: Any, desired_classes: Any, can_choose_root: bool = ..., user_perm: Optional[Any] = ...): ...
def browse(request: Any, parent_page_id: Optional[Any] = ...): ...
def search(request: Any, parent_page_id: Optional[Any] = ...): ...
def external_link(request: Any): ...
def anchor_link(request: Any): ...
def email_link(request: Any): ...
def phone_link(request: Any): ...
