from typing import Any
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.search.backends import get_search_backend as get_search_backend
from wagtail.search.index import class_is_indexed as class_is_indexed

class SearchableListMixin:
    search_box_placeholder: Any = ...
    search_fields: Any = ...
    def get_search_form(self): ...
    def get_queryset(self): ...
    def get_context_data(self, **kwargs: Any): ...

class Echo:
    def write(self, value: Any): ...

def list_to_str(value: Any): ...

class SpreadsheetExportMixin:
    FORMAT_XLSX: str = ...
    FORMAT_CSV: str = ...
    FORMATS: Any = ...
    list_export: Any = ...
    custom_field_preprocess: Any = ...
    custom_value_preprocess: Any = ...
    export_headings: Any = ...
    def get_filename(self): ...
    def to_row_dict(self, item: Any): ...
    def multigetattr(self, item: Any, multi_attribute: Any): ...
    def get_preprocess_function(self, field: Any, value: Any, export_format: Any): ...
    def write_xlsx_row(self, worksheet: Any, row_dict: Any, row_number: Any) -> None: ...
    def write_csv_row(self, writer: Any, row_dict: Any): ...
    def get_heading(self, queryset: Any, field: Any): ...
    def stream_csv(self, queryset: Any) -> None: ...
    def write_xlsx(self, queryset: Any, output: Any) -> None: ...
    def write_xlsx_response(self, queryset: Any): ...
    def write_csv_response(self, queryset: Any): ...
    def as_spreadsheet(self, queryset: Any, spreadsheet_format: Any): ...
    def get_export_url(self, format: Any): ...
    @property
    def xlsx_export_url(self): ...
    @property
    def csv_export_url(self): ...
