from typing import Any, Optional
from wagtail.admin import messages as messages
from wagtail.admin.edit_handlers import ObjectList as ObjectList, extract_panel_definitions_from_model_class as extract_panel_definitions_from_model_class
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.core import hooks as hooks
from wagtail.core.models import Locale as Locale, TranslatableMixin as TranslatableMixin
from wagtail.search.backends import get_search_backend as get_search_backend
from wagtail.search.index import class_is_indexed as class_is_indexed
from wagtail.snippets.action_menu import SnippetActionMenu as SnippetActionMenu
from wagtail.snippets.models import get_snippet_models as get_snippet_models
from wagtail.snippets.permissions import get_permission_name as get_permission_name, user_can_edit_snippet_type as user_can_edit_snippet_type

def get_snippet_model_from_url_params(app_name: Any, model_name: Any): ...

SNIPPET_EDIT_HANDLERS: Any

def get_snippet_edit_handler(model: Any): ...
def index(request: Any): ...
def list(request: Any, app_label: Any, model_name: Any): ...
def create(request: Any, app_label: Any, model_name: Any): ...
def edit(request: Any, app_label: Any, model_name: Any, pk: Any): ...
def delete(request: Any, app_label: Any, model_name: Any, pk: Optional[Any] = ...): ...
def usage(request: Any, app_label: Any, model_name: Any, pk: Any): ...
