from typing import Any
from wagtail.core import hooks as hooks

class ViewSetRegistry:
    viewsets: Any = ...
    def __init__(self) -> None: ...
    def populate(self) -> None: ...
    def register(self, viewset_cls: Any): ...
    def get_urlpatterns(self): ...

viewsets: Any
