from typing import Any

class ViewSet:
    name: Any = ...
    url_prefix: Any = ...
    def __init__(self, name: Any, **kwargs: Any) -> None: ...
    def get_urlpatterns(self): ...
    def get_url_name(self, view_name: Any): ...
