from .base import ViewSet as ViewSet
from typing import Any
from wagtail.admin.views import generic as generic
from wagtail.core.permissions import ModelPermissionPolicy as ModelPermissionPolicy

class ModelViewSet(ViewSet):
    icon: str = ...
    index_view_class: Any = ...
    add_view_class: Any = ...
    edit_view_class: Any = ...
    delete_view_class: Any = ...
    @property
    def permission_policy(self): ...
    @property
    def index_view(self): ...
    @property
    def add_view(self): ...
    @property
    def edit_view(self): ...
    @property
    def delete_view(self): ...
    def formfield_for_dbfield(self, db_field: Any, **kwargs: Any): ...
    def get_form_class(self, for_update: bool = ...): ...
    def get_urlpatterns(self): ...
