from django.db.models import Model
from typing import Any
from wagtail.core.rich_text.feature_registry import FeatureRegistry as FeatureRegistry
from wagtail.core.rich_text.rewriters import EmbedRewriter as EmbedRewriter, LinkRewriter as LinkRewriter, MultiRuleRewriter as MultiRuleRewriter

features: Any
FRONTEND_REWRITER: Any

def expand_db_html(html: Any): ...
def get_text_for_indexing(richtext: Any): ...

class RichText:
    source: Any = ...
    def __init__(self, source: Any) -> None: ...
    def __html__(self): ...
    def __bool__(self): ...

class EntityHandler:
    @staticmethod
    def get_model() -> None: ...
    @classmethod
    def get_instance(cls: Any, attrs: dict) -> Model: ...
    @staticmethod
    def expand_db_attributes(attrs: dict) -> str: ...

class LinkHandler(EntityHandler): ...
class EmbedHandler(EntityHandler): ...
