from typing import Any
from wagtail.core.models import Page as Page
from wagtail.core.rich_text import LinkHandler as LinkHandler

class PageLinkHandler(LinkHandler):
    identifier: str = ...
    @staticmethod
    def get_model(): ...
    @classmethod
    def get_instance(cls, attrs: Any): ...
    @classmethod
    def expand_db_attributes(cls, attrs: Any): ...
