from django import forms
from typing import Any
from wagtail.admin import messages as messages
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.admin.rich_text import get_rich_text_editor_widget as get_rich_text_editor_widget
from wagtail.admin.widgets import AdminAutoHeightTextInput as AdminAutoHeightTextInput, AdminDateInput as AdminDateInput, AdminDateTimeInput as AdminDateTimeInput, AdminPageChooser as AdminPageChooser, AdminTimeInput as AdminTimeInput
from wagtail.core.models import Page as Page
from wagtail.documents.widgets import AdminDocumentChooser as AdminDocumentChooser
from wagtail.images.widgets import AdminImageChooser as AdminImageChooser
from wagtail.snippets.widgets import AdminSnippetChooser as AdminSnippetChooser

class ExampleForm(forms.Form):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CHOICES: Any = ...
    text: Any = ...
    auto_height_text: Any = ...
    default_rich_text: Any = ...
    url: Any = ...
    email: Any = ...
    date: Any = ...
    time: Any = ...
    datetime: Any = ...
    select: Any = ...
    radio_select: Any = ...
    boolean: Any = ...
    page_chooser: Any = ...
    image_chooser: Any = ...
    document_chooser: Any = ...
    snippet_chooser: Any = ...

def index(request: Any): ...
