from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from typing import Any, Optional

class LoginForm(AuthenticationForm):
    username: Any = ...
    password: Any = ...
    def __init__(self, request: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    @property
    def extra_fields(self) -> None: ...

class PasswordResetForm(PasswordResetForm):
    email: Any = ...
