from django import forms
from django.core import validators
from typing import Any

class URLOrAbsolutePathValidator(validators.URLValidator):
    @staticmethod
    def is_absolute_path(value: Any): ...
    def __call__(self, value: Any): ...

class URLOrAbsolutePathField(forms.URLField):
    widget: Any = ...
    default_validators: Any = ...
    def to_python(self, value: Any): ...

class ExternalLinkChooserForm(forms.Form):
    url: Any = ...
    link_text: Any = ...

class AnchorLinkChooserForm(forms.Form):
    url: Any = ...
    link_text: Any = ...

class EmailLinkChooserForm(forms.Form):
    email_address: Any = ...
    link_text: Any = ...

class PhoneLinkChooserForm(forms.Form):
    phone_number: Any = ...
    link_text: Any = ...
