from taggit.forms import TagField as TaggitTagField
from typing import Any
from wagtail.admin.widgets import AdminTagWidget as AdminTagWidget

class TagField(TaggitTagField):
    widget: Any = ...
    tag_model: Any = ...
    free_tagging: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clean(self, value: Any): ...
