from django import forms
from typing import Any
from wagtail.core.models import BaseViewRestriction as BaseViewRestriction

class BaseViewRestrictionForm(forms.ModelForm):
    restriction_type: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clean_password(self): ...
    def clean_groups(self): ...
