from django import forms
from typing import Any, Optional
from wagtail.admin import widgets as widgets
from wagtail.admin.edit_handlers import FieldPanel as FieldPanel, InlinePanel as InlinePanel, ObjectList as ObjectList
from wagtail.admin.forms import WagtailAdminModelForm as WagtailAdminModelForm
from wagtail.admin.widgets.workflows import AdminTaskChooser as AdminTaskChooser
from wagtail.core.models import Page as Page, Task as Task, Workflow as Workflow, WorkflowPage as WorkflowPage
from wagtail.core.utils import get_model_string as get_model_string

class TaskChooserSearchForm(forms.Form):
    q: Any = ...
    task_type_choices: Any = ...
    def __init__(self, *args: Any, task_type_choices: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def is_searching(self): ...
    def task_model(self): ...
    def specific_task_model_selected(self): ...

class WorkflowPageForm(forms.ModelForm):
    page: Any = ...
    def clean(self) -> None: ...
    def save(self, commit: bool = ...) -> None: ...

class BaseWorkflowPagesFormSet(forms.BaseInlineFormSet):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def empty_form(self): ...
    def clean(self) -> None: ...

WorkflowPagesFormSet: Any

class BaseTaskForm(forms.ModelForm): ...

def get_task_form_class(task_model: Any, for_edit: bool = ...): ...
def get_workflow_edit_handler(): ...
