from typing import Any

class RemovedInWagtail212Warning(DeprecationWarning): ...
removed_in_next_version_warning = RemovedInWagtail212Warning

class RemovedInWagtail213Warning(PendingDeprecationWarning): ...

class MovedDefinitionHandler:
    real_module: Any = ...
    moved_definitions: Any = ...
    warning_class: Any = ...
    def __init__(self, real_module: Any, moved_definitions: Any, warning_class: Any) -> None: ...
    def __getattr__(self, name: Any): ...
