from setuptools import Command
from setuptools.command.bdist_egg import bdist_egg
from setuptools.command.sdist import sdist as base_sdist
from typing import Any
from wagtail import __semver__ as __semver__

class assets_mixin:
    def compile_assets(self) -> None: ...
    def publish_assets(self) -> None: ...
    def bump_client_version(self) -> None: ...

class assets(Command, assets_mixin):
    user_options: Any = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...

class sdist(base_sdist, assets_mixin):
    def run(self) -> None: ...

class check_bdist_egg(bdist_egg):
    sentinel_dir: str = ...
    def run(self) -> None: ...
