from typing import Any, Optional

def get_version(version: Any): ...
def get_main_version(version: Optional[Any] = ...): ...
def get_complete_version(version: Optional[Any] = ...): ...
def get_semver_version(version: Any): ...
