from django.forms.widgets import Widget
from typing import Any, Optional

class WidgetWithScript(Widget):
    def render_html(self, name: Any, value: Any, attrs: Any): ...
    def render(self, name: Any, value: Any, attrs: Optional[Any] = ..., renderer: Optional[Any] = ...): ...
    def render_js_init(self, id_: Any, name: Any, value: Any): ...
