from typing import Any
from wagtail.admin.edit_handlers import EditHandler as EditHandler

class FormSubmissionsPanel(EditHandler):
    template: str = ...
    def render(self): ...
    heading: Any = ...
    def on_model_bound(self) -> None: ...
