import django.forms
from typing import Any
from wagtail.admin.forms import WagtailAdminPageForm as WagtailAdminPageForm
from wagtail.contrib.forms.utils import get_field_clean_name as get_field_clean_name

class BaseForm(django.forms.Form):
    user: Any = ...
    page: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class FormBuilder:
    fields: Any = ...
    def __init__(self, fields: Any) -> None: ...
    def create_singleline_field(self, field: Any, options: Any): ...
    def create_multiline_field(self, field: Any, options: Any): ...
    def create_date_field(self, field: Any, options: Any): ...
    def create_datetime_field(self, field: Any, options: Any): ...
    def create_email_field(self, field: Any, options: Any): ...
    def create_url_field(self, field: Any, options: Any): ...
    def create_number_field(self, field: Any, options: Any): ...
    def create_dropdown_field(self, field: Any, options: Any): ...
    def create_multiselect_field(self, field: Any, options: Any): ...
    def create_radio_field(self, field: Any, options: Any): ...
    def create_checkboxes_field(self, field: Any, options: Any): ...
    def create_checkbox_field(self, field: Any, options: Any): ...
    def create_hidden_field(self, field: Any, options: Any): ...
    def get_create_field_function(self, type: Any): ...
    @property
    def formfields(self): ...
    def get_field_options(self, field: Any): ...
    def get_form_class(self): ...

class SelectDateForm(django.forms.Form):
    date_from: Any = ...
    date_to: Any = ...

class WagtailAdminFormPageForm(WagtailAdminPageForm):
    def clean(self) -> None: ...
