from typing import Any
from wagtail.core import hooks as hooks
from wagtail.core.models import UserPagePermissionsProxy as UserPagePermissionsProxy, get_page_models as get_page_models
from wagtail.core.utils import safe_snake_case as safe_snake_case

def get_field_clean_name(label: Any): ...
def get_form_types(): ...
def get_forms_for_user(user: Any): ...
