from typing import Any, Optional

class APIField:
    name: Any = ...
    serializer: Any = ...
    def __init__(self, name: Any, serializer: Optional[Any] = ...) -> None: ...
    def __hash__(self) -> Any: ...
