from typing import Any

class Format:
    def get_title(self): ...
    def create_dataset(self, in_stream: Any) -> None: ...
    def export_data(self, dataset: Any, **kwargs: Any) -> None: ...
    def is_binary(self): ...
    def get_read_mode(self): ...
    def get_extension(self): ...
    def get_content_type(self): ...
    @classmethod
    def is_available(cls): ...
    def can_import(self): ...
    def can_export(self): ...

class TablibFormat(Format):
    TABLIB_MODULE: Any = ...
    CONTENT_TYPE: str = ...
    def get_format(self): ...
    @classmethod
    def is_available(cls): ...
    def get_title(self): ...
    def create_dataset(self, in_stream: Any, **kwargs: Any): ...
    def export_data(self, dataset: Any, **kwargs: Any): ...
    def get_extension(self): ...
    def get_content_type(self): ...
    def can_import(self): ...
    def can_export(self): ...

class TextFormat(TablibFormat):
    def get_read_mode(self): ...
    def is_binary(self): ...

class CSV(TextFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...
    def create_dataset(self, in_stream: Any, **kwargs: Any): ...

class JSON(TextFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...

class YAML(TextFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...

class TSV(TextFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...
    def create_dataset(self, in_stream: Any, **kwargs: Any): ...

class ODS(TextFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...

class HTML(TextFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...

class XLS(TablibFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...
    def create_dataset(self, in_stream: Any): ...

class XLSX(TablibFormat):
    TABLIB_MODULE: str = ...
    CONTENT_TYPE: str = ...
    def create_dataset(self, in_stream: Any): ...

DEFAULT_FORMATS: Any
