from django.db import models
from typing import Any, Optional
from wagtail.core.models import Page as Page

class Redirect(models.Model):
    old_path: Any = ...
    site: Any = ...
    is_permanent: Any = ...
    redirect_page: Any = ...
    redirect_link: Any = ...
    @property
    def title(self): ...
    @property
    def link(self): ...
    def get_is_permanent_display(self): ...
    @classmethod
    def get_for_site(cls, site: Optional[Any] = ...): ...
    @staticmethod
    def add_redirect(old_path: Any, redirect_to: Optional[Any] = ..., is_permanent: bool = ...): ...
    @staticmethod
    def normalise_path(url: Any): ...
    def clean(self) -> None: ...
    class Meta:
        verbose_name: Any = ...
        unique_together: Any = ...
