from typing import Any, Optional

class BaseStorage:
    name: Any = ...
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def save(self, data: Any, mode: str = ...) -> None: ...
    def read(self, read_mode: str = ...) -> None: ...
    def remove(self) -> None: ...

class TempFolderStorage(BaseStorage):
    name: Any = ...
    def open(self, mode: str = ...): ...
    def save(self, data: Any, mode: str = ...) -> None: ...
    def read(self, mode: str = ...): ...
    def remove(self) -> None: ...
    def get_full_path(self): ...

class CacheStorage(BaseStorage):
    CACHE_LIFETIME: int = ...
    CACHE_PREFIX: str = ...
    name: Any = ...
    def save(self, data: Any, mode: Optional[Any] = ...) -> None: ...
    def read(self, read_mode: str = ...): ...
    def remove(self) -> None: ...

class MediaStorage(BaseStorage):
    MEDIA_FOLDER: str = ...
    name: Any = ...
    def save(self, data: Any, mode: Optional[Any] = ...) -> None: ...
    def read(self, read_mode: str = ...): ...
    def remove(self) -> None: ...
    def get_full_path(self): ...
