from typing import Any
from wagtail.contrib.redirects.base_formats import DEFAULT_FORMATS as DEFAULT_FORMATS
from wagtail.contrib.redirects.tmp_storages import CacheStorage as CacheStorage, TempFolderStorage as TempFolderStorage

def write_to_file_storage(import_file: Any, input_format: Any): ...
def get_supported_extensions(): ...
def get_format_cls_by_extension(extension: Any): ...
def get_import_formats(): ...
def get_file_storage(): ...

class RedirectsCacheStorage(CacheStorage):
    CACHE_PREFIX: str = ...
