from typing import Any
from wagtail.admin import messages as messages
from wagtail.admin.auth import PermissionPolicyChecker as PermissionPolicyChecker
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.contrib.redirects import models as models
from wagtail.contrib.redirects.base_formats import DEFAULT_FORMATS as DEFAULT_FORMATS
from wagtail.contrib.redirects.forms import ConfirmImportForm as ConfirmImportForm, ImportForm as ImportForm, RedirectForm as RedirectForm
from wagtail.contrib.redirects.permissions import permission_policy as permission_policy
from wagtail.contrib.redirects.utils import get_file_storage as get_file_storage, get_format_cls_by_extension as get_format_cls_by_extension, get_import_formats as get_import_formats, get_supported_extensions as get_supported_extensions, write_to_file_storage as write_to_file_storage

permission_checker: Any

def index(request: Any): ...
def edit(request: Any, redirect_id: Any): ...
def delete(request: Any, redirect_id: Any): ...
def add(request: Any): ...
def start_import(request: Any): ...
def process_import(request: Any): ...
def create_redirects_from_dataset(dataset: Any, config: Any): ...
def to_readable_errors(error: Any): ...
