from .base import EmbedFinder as EmbedFinder
from typing import Any, Optional
from wagtail.embeds.exceptions import EmbedException as EmbedException, EmbedNotFoundException as EmbedNotFoundException

class EmbedlyException(EmbedException): ...
class AccessDeniedEmbedlyException(EmbedlyException): ...

class EmbedlyFinder(EmbedFinder):
    key: Any = ...
    def __init__(self, key: Optional[Any] = ...) -> None: ...
    def get_key(self): ...
    def accept(self, url: Any): ...
    def find_embed(self, url: Any, max_width: Optional[Any] = ..., key: Optional[Any] = ...): ...
embed_finder_class = EmbedlyFinder
