from .base import EmbedFinder as EmbedFinder
from typing import Any, Optional
from wagtail.embeds.exceptions import EmbedException as EmbedException, EmbedNotFoundException as EmbedNotFoundException

class AccessDeniedFacebookOEmbedException(EmbedException): ...

class FacebookOEmbedFinder(EmbedFinder):
    facebook_video: Any = ...
    facebook_post: Any = ...
    app_id: Any = ...
    app_secret: Any = ...
    omitscript: Any = ...
    def __init__(self, omitscript: bool = ..., app_id: Optional[Any] = ..., app_secret: Optional[Any] = ...) -> None: ...
    def accept(self, url: Any): ...
    def find_embed(self, url: Any, max_width: Optional[Any] = ...): ...
embed_finder_class = FacebookOEmbedFinder
