from .base import EmbedFinder as EmbedFinder
from typing import Any, Optional
from wagtail.embeds.exceptions import EmbedNotFoundException as EmbedNotFoundException
from wagtail.embeds.oembed_providers import all_providers as all_providers

class OEmbedFinder(EmbedFinder):
    options: Any = ...
    def __init__(self, providers: Optional[Any] = ..., options: Optional[Any] = ...) -> None: ...
    def accept(self, url: Any): ...
    def find_embed(self, url: Any, max_width: Optional[Any] = ...): ...
embed_finder_class = OEmbedFinder
