from django.core.management.base import BaseCommand
from typing import Any
from wagtail.core.models import Collection as Collection, Page as Page

class Command(BaseCommand):
    help: str = ...
    stealth_options: Any = ...
    def add_arguments(self, parser: Any) -> None: ...
    def numberlist_to_string(self, numberlist: Any): ...
    def handle(self, **options: Any) -> None: ...
    def handle_model(self, model: Any, model_name: Any, model_name_plural: Any, any_problems_fixed: Any, options: Any) -> None: ...
