from django.core.management.base import BaseCommand
from typing import Any, Optional
from wagtail.core.models import PageRevision as PageRevision, WorkflowState as WorkflowState

workflow_support: bool

class Command(BaseCommand):
    help: str = ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...

def purge_revisions(days: Optional[Any] = ...): ...
