from django.core.management.base import BaseCommand
from typing import Any, Optional
from wagtail.core.models import Page as Page

class Command(BaseCommand):
    help: str = ...
    def set_subtree(self, root: Any, parent: Optional[Any] = ...) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...
