from .filters import ForExplorerFilter as ForExplorerFilter, HasChildrenFilter as HasChildrenFilter
from .serializers import AdminPageSerializer as AdminPageSerializer
from typing import Any
from wagtail.api.v2.views import PagesAPIViewSet as PagesAPIViewSet
from wagtail.core.models import Page as Page

class PagesAdminAPIViewSet(PagesAPIViewSet):
    base_serializer_class: Any = ...
    authentication_classes: Any = ...
    filter_backends: Any = ...
    meta_fields: Any = ...
    body_fields: Any = ...
    listing_default_fields: Any = ...
    detail_only_fields: Any = ...
    known_query_parameters: Any = ...
    @classmethod
    def get_detail_default_fields(cls, model: Any): ...
    def get_root_page(self): ...
    def get_base_queryset(self): ...
    def get_queryset(self): ...
    def get_type_info(self): ...
    def listing_view(self, request: Any): ...
    def detail_view(self, request: Any, pk: Any): ...
