from ... import get_document_model as get_document_model
from .serializers import DocumentSerializer as DocumentSerializer
from typing import Any
from wagtail.api.v2.filters import FieldsFilter as FieldsFilter, OrderingFilter as OrderingFilter, SearchFilter as SearchFilter
from wagtail.api.v2.views import BaseAPIViewSet as BaseAPIViewSet

class DocumentsAPIViewSet(BaseAPIViewSet):
    base_serializer_class: Any = ...
    filter_backends: Any = ...
    body_fields: Any = ...
    meta_fields: Any = ...
    listing_default_fields: Any = ...
    nested_default_fields: Any = ...
    name: str = ...
    model: Any = ...
