from django import template
from typing import Any, Optional
from wagtail.images.models import Filter as Filter
from wagtail.images.shortcuts import get_rendition_or_not_found as get_rendition_or_not_found
from wagtail.images.views.serve import generate_image_url as generate_image_url

register: Any
allowed_filter_pattern: Any

def image(parser: Any, token: Any): ...

class ImageNode(template.Node):
    image_expr: Any = ...
    output_var_name: Any = ...
    attrs: Any = ...
    filter_spec: Any = ...
    def __init__(self, image_expr: Any, filter_spec: Any, output_var_name: Optional[Any] = ..., attrs: Any = ...) -> None: ...
    def filter(self): ...
    def render(self, context: Any): ...

def image_url(image: Any, filter_spec: Any, viewname: str = ...): ...
