from django import forms
from typing import Any
from wagtail.admin.staticfiles import versioned_static as versioned_static
from wagtail.core.models import Site as Site

class SiteSwitchForm(forms.Form):
    site: Any = ...
    @property
    def media(self): ...
    def __init__(self, current_site: Any, model: Any, **kwargs: Any) -> None: ...
    @classmethod
    def get_change_url(cls, site: Any, model: Any): ...
