from jinja2.ext import Extension
from typing import Any
from wagtail.contrib.settings.registry import registry as registry
from wagtail.core.models import Site as Site

settings_cache: Any

class ContextCache(dict):
    def __missing__(self, key: Any): ...

class SiteSettings(dict):
    site: Any = ...
    def __init__(self, site: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __missing__(self, key: Any): ...

def get_setting(context: Any, model_string: Any, use_default_site: bool = ...): ...

class SettingsExtension(Extension):
    def __init__(self, environment: Any) -> None: ...
settings = SettingsExtension
