from .registry import register_setting as register_setting
from django.db import models
from typing import Any, Optional

class BaseSetting(models.Model):
    select_related: Any = ...
    site: Any = ...
    class Meta:
        abstract: bool = ...
    @classmethod
    def base_queryset(cls): ...
    @classmethod
    def for_site(cls, site: Any): ...
    @classmethod
    def for_request(cls, request: Any): ...
    @classmethod
    def get_cache_attr_name(cls): ...
    page_url: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_page_url(self, attribute_name: Any, request: Optional[Any] = ...): ...
