from .permissions import user_can_edit_setting_type as user_can_edit_setting_type
from typing import Any, Optional
from wagtail.admin.menu import MenuItem as MenuItem
from wagtail.core import hooks as hooks

class SettingMenuItem(MenuItem):
    model: Any = ...
    def __init__(self, model: Any, icon: str = ..., classnames: str = ..., **kwargs: Any) -> None: ...
    def is_shown(self, request: Any): ...

class Registry(list):
    def register(self, model: Any, **kwargs: Any): ...
    def register_decorator(self, model: Optional[Any] = ..., **kwargs: Any): ...
    def get_by_natural_key(self, app_label: Any, model_name: Any): ...

registry: Any
register_setting: Any
