from .forms import SiteSwitchForm as SiteSwitchForm
from .permissions import user_can_edit_setting_type as user_can_edit_setting_type
from .registry import registry as registry
from typing import Any
from wagtail.admin import messages as messages
from wagtail.admin.edit_handlers import ObjectList as ObjectList, TabbedInterface as TabbedInterface, extract_panel_definitions_from_model_class as extract_panel_definitions_from_model_class
from wagtail.core.models import Site as Site

def get_model_from_url_params(app_name: Any, model_name: Any): ...
def get_setting_edit_handler(model: Any): ...
def edit_current_site(request: Any, app_name: Any, model_name: Any): ...
def edit(request: Any, app_name: Any, model_name: Any, site_pk: Any): ...
