from ..v2.views import ImagesAPIViewSet as ImagesAPIViewSet
from .serializers import AdminImageSerializer as AdminImageSerializer
from typing import Any

class ImagesAdminAPIViewSet(ImagesAPIViewSet):
    base_serializer_class: Any = ...
    body_fields: Any = ...
    listing_default_fields: Any = ...
