from django import template
from typing import Any, Optional
from wagtail import VERSION as VERSION
from wagtail.core.models import Page as Page, Site as Site
from wagtail.core.rich_text import RichText as RichText, expand_db_html as expand_db_html
from wagtail.utils.version import get_main_version as get_main_version

register: Any

def pageurl(context: Any, page: Any, fallback: Optional[Any] = ...): ...
def slugurl(context: Any, slug: Any): ...
def wagtail_version(): ...
def wagtail_documentation_path(): ...
def wagtail_release_notes_path(): ...
def richtext(value: Any): ...

class IncludeBlockNode(template.Node):
    block_var: Any = ...
    extra_context: Any = ...
    use_parent_context: Any = ...
    def __init__(self, block_var: Any, extra_context: Any, use_parent_context: Any) -> None: ...
    def render(self, context: Any): ...

def include_block(parser: Any, token: Any): ...
def wagtail_site(context: Any): ...
