from django import forms
from typing import Any, Optional

class ButtonSelect(forms.Select):
    input_type: str = ...
    template_name: str = ...
    option_template_name: str = ...

class BooleanButtonSelect(ButtonSelect):
    def __init__(self, attrs: Optional[Any] = ...) -> None: ...
    def format_value(self, value: Any): ...
    def value_from_datadict(self, data: Any, files: Any, name: Any): ...
