from typing import Any, Optional
from wagtail.core import hooks as hooks
from wagtail.core.utils import accepts_kwarg as accepts_kwarg
from wagtail.utils.deprecation import RemovedInWagtail212Warning as RemovedInWagtail212Warning

class Button:
    show: bool = ...
    label: Any = ...
    url: Any = ...
    classes: Any = ...
    attrs: Any = ...
    priority: Any = ...
    def __init__(self, label: Any, url: Any, classes: Any = ..., attrs: Any = ..., priority: int = ...) -> None: ...
    def render(self): ...
    def __lt__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...

class ListingButton(Button):
    def __init__(self, label: Any, url: Any, classes: Any = ..., **kwargs: Any) -> None: ...

class PageListingButton(ListingButton): ...

class BaseDropdownMenuButton(Button):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def dropdown_buttons(self) -> None: ...
    def render(self): ...

class ButtonWithDropdownFromHook(BaseDropdownMenuButton):
    template_name: str = ...
    hook_name: Any = ...
    page: Any = ...
    page_perms: Any = ...
    is_parent: Any = ...
    next_url: Any = ...
    def __init__(self, label: Any, hook_name: Any, page: Any, page_perms: Any, is_parent: Any, next_url: Optional[Any] = ..., **kwargs: Any) -> None: ...
    @property
    def show(self): ...
    def dropdown_buttons(self): ...
