from django.forms import widgets
from typing import Any, Optional
from wagtail.admin.staticfiles import versioned_static as versioned_static
from wagtail.core.models import Page as Page
from wagtail.utils.widgets import WidgetWithScript as WidgetWithScript

class AdminChooser(WidgetWithScript, widgets.Input):
    input_type: str = ...
    choose_one_text: Any = ...
    choose_another_text: Any = ...
    clear_choice_text: Any = ...
    link_to_chosen_text: Any = ...
    show_edit_link: bool = ...
    show_clear_link: bool = ...
    is_hidden: bool = ...
    def get_instance(self, model_class: Any, value: Any): ...
    def get_instance_and_id(self, model_class: Any, value: Any): ...
    def value_from_datadict(self, data: Any, files: Any, name: Any): ...
    def __init__(self, **kwargs: Any) -> None: ...

class AdminPageChooser(AdminChooser):
    choose_one_text: Any = ...
    choose_another_text: Any = ...
    link_to_chosen_text: Any = ...
    user_perms: Any = ...
    target_models: Any = ...
    can_choose_root: Any = ...
    def __init__(self, target_models: Optional[Any] = ..., can_choose_root: bool = ..., user_perms: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def render_html(self, name: Any, value: Any, attrs: Any): ...
    def render_js_init(self, id_: Any, name: Any, value: Any): ...
    @property
    def media(self): ...
