from django import forms
from typing import Any, Optional
from wagtail.admin.staticfiles import versioned_static as versioned_static

class FilteredSelect(forms.Select):
    filter_field: Any = ...
    def __init__(self, attrs: Optional[Any] = ..., choices: Any = ..., filter_field: str = ...) -> None: ...
    def build_attrs(self, base_attrs: Any, extra_attrs: Optional[Any] = ...): ...
    def optgroups(self, name: Any, value: Any, attrs: Optional[Any] = ...): ...
    def create_option(self, name: Any, value: Any, label: Any, selected: Any, index: Any, subindex: Optional[Any] = ..., attrs: Optional[Any] = ..., filter_value: Optional[Any] = ...): ...
    @property
    def media(self): ...
