from taggit.forms import TagWidget
from typing import Any

class AdminTagWidget(TagWidget):
    template_name: str = ...
    tag_model: Any = ...
    free_tagging: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_context(self, name: Any, value: Any, attrs: Any): ...
