from typing import Any
from wagtail.admin import messages as messages
from wagtail.core.models import GroupPagePermission as GroupPagePermission

def users_with_page_permission(page: Any, permission_type: Any, include_superusers: bool = ...): ...
def permission_denied(request: Any): ...
def user_passes_test(test: Any): ...
def permission_required(permission_name: Any): ...
def any_permission_required(*perms: Any): ...

class PermissionPolicyChecker:
    policy: Any = ...
    def __init__(self, policy: Any) -> None: ...
    def require(self, action: Any): ...
    def require_any(self, *actions: Any): ...

def user_has_any_page_permission(user: Any): ...
def reject_request(request: Any): ...
def require_admin_access(view_func: Any): ...
