from typing import Any
from wagtail.core import hooks as hooks

class LogActionRegistry:
    has_scanned_for_actions: bool = ...
    actions: Any = ...
    choices: Any = ...
    messages: Any = ...
    def __init__(self) -> None: ...
    def scan_for_actions(self): ...
    def get_actions(self): ...
    def register_action(self, action: Any, label: Any, message: Any) -> None: ...
    def get_choices(self): ...
    def get_messages(self): ...
    def format_message(self, log_entry: Any): ...
    def get_action_label(self, action: Any): ...

registry: Any
