from django.forms import MediaDefiningClass
from typing import Any, Optional
from wagtail.core import hooks as hooks

class MenuItem(metaclass=MediaDefiningClass):
    template: str = ...
    label: Any = ...
    url: Any = ...
    classnames: Any = ...
    icon_name: Any = ...
    name: Any = ...
    order: Any = ...
    attr_string: Any = ...
    def __init__(self, label: Any, url: Any, name: Optional[Any] = ..., classnames: str = ..., icon_name: str = ..., attrs: Optional[Any] = ..., order: int = ...) -> None: ...
    def is_shown(self, request: Any): ...
    def is_active(self, request: Any): ...
    def get_context(self, request: Any): ...
    def render_html(self, request: Any): ...

class Menu:
    register_hook_name: Any = ...
    construct_hook_name: Any = ...
    def __init__(self, register_hook_name: Any, construct_hook_name: Optional[Any] = ...) -> None: ...
    @property
    def registered_menu_items(self): ...
    def menu_items_for_request(self, request: Any): ...
    def active_menu_items(self, request: Any): ...
    @property
    def media(self): ...
    def render_html(self, request: Any): ...

class SubmenuMenuItem(MenuItem):
    template: str = ...
    menu: Any = ...
    def __init__(self, label: Any, menu: Any, **kwargs: Any) -> None: ...
    def is_shown(self, request: Any): ...
    def is_active(self, request: Any): ...
    def get_context(self, request: Any): ...

class AdminOnlyMenuItem(MenuItem):
    def is_shown(self, request: Any): ...

admin_menu: Any
settings_menu: Any
reports_menu: Any
