from typing import Any
from wagtail.core.models import Page as Page

def get_pages_with_direct_explore_permission(user: Any): ...
def get_explorable_root_page(user: Any): ...
def get_site_for_user(user: Any): ...
