from django.forms import MediaDefiningClass
from typing import Any, Optional
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.core import hooks as hooks

class SearchArea(metaclass=MediaDefiningClass):
    template: str = ...
    label: Any = ...
    url: Any = ...
    classnames: Any = ...
    name: Any = ...
    order: Any = ...
    attr_string: Any = ...
    def __init__(self, label: Any, url: Any, name: Optional[Any] = ..., classnames: str = ..., attrs: Optional[Any] = ..., order: int = ...) -> None: ...
    def __lt__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def is_shown(self, request: Any): ...
    def is_active(self, request: Any, current: Optional[Any] = ...): ...
    def render_html(self, request: Any, query: Any, current: Optional[Any] = ...): ...

class Search:
    register_hook_name: Any = ...
    construct_hook_name: Any = ...
    def __init__(self, register_hook_name: Any, construct_hook_name: Optional[Any] = ...) -> None: ...
    def registered_search_areas(self): ...
    def search_items_for_request(self, request: Any): ...
    def active_search(self, request: Any, current: Optional[Any] = ...): ...
    @property
    def media(self): ...
    def render_html(self, request: Any, current: Optional[Any] = ...): ...

admin_search_areas: Any
