from typing import Any
from wagtail.admin.auth import user_has_any_page_permission as user_has_any_page_permission
from wagtail.admin.navigation import get_site_for_user as get_site_for_user
from wagtail.core import hooks as hooks
from wagtail.core.models import Page as Page, Site as Site

class SummaryItem:
    order: int = ...
    request: Any = ...
    def __init__(self, request: Any) -> None: ...
    def get_context(self): ...
    def render(self): ...
    def is_shown(self): ...

class PagesSummaryItem(SummaryItem):
    order: int = ...
    template: str = ...
    def get_context(self): ...
    def is_shown(self): ...

class SiteSummaryPanel:
    name: str = ...
    order: int = ...
    request: Any = ...
    summary_items: Any = ...
    def __init__(self, request: Any) -> None: ...
    def render(self): ...
