from typing import Any

class BaseItem:
    template: str = ...
    def render(self, request: Any): ...

class AdminItem(BaseItem):
    template: str = ...
    def render(self, request: Any): ...

class AddPageItem(BaseItem):
    template: str = ...
    page: Any = ...
    parent_page: Any = ...
    def __init__(self, page: Any) -> None: ...
    def render(self, request: Any): ...

class ExplorePageItem(BaseItem):
    template: str = ...
    page: Any = ...
    parent_page: Any = ...
    def __init__(self, page: Any) -> None: ...
    def render(self, request: Any): ...

class EditPageItem(BaseItem):
    template: str = ...
    page: Any = ...
    def __init__(self, page: Any) -> None: ...
    def render(self, request: Any): ...

class ModeratePageItem(BaseItem):
    revision: Any = ...
    def __init__(self, revision: Any) -> None: ...
    def render(self, request: Any): ...

class ApproveModerationEditPageItem(ModeratePageItem):
    template: str = ...

class RejectModerationEditPageItem(ModeratePageItem):
    template: str = ...
