from typing import Any
from wagtail.admin import messages as messages
from wagtail.admin.mail import send_notification as send_notification
from wagtail.core.models import PageRevision as PageRevision

def approve_moderation(request: Any, revision_id: Any): ...
def reject_moderation(request: Any, revision_id: Any): ...
def preview_for_moderation(request: Any, revision_id: Any): ...
