from django.views.generic import View
from typing import Any
from wagtail.core.models import Page as Page

def view_draft(request: Any, page_id: Any): ...

class PreviewOnEdit(View):
    http_method_names: Any = ...
    preview_expiration_timeout: Any = ...
    session_key_prefix: str = ...
    def remove_old_preview_data(self) -> None: ...
    @property
    def session_key(self): ...
    def get_page(self): ...
    def get_form(self, page: Any, query_dict: Any): ...
    def post(self, request: Any, *args: Any, **kwargs: Any): ...
    def error_response(self, page: Any): ...
    def get(self, request: Any, *args: Any, **kwargs: Any): ...

class PreviewOnCreate(PreviewOnEdit):
    def get_page(self): ...
    def get_form(self, page: Any, query_dict: Any): ...
