from typing import Any
from wagtail.admin.views import generic as generic, mixins as mixins
from wagtail.admin.viewsets.model import ModelViewSet as ModelViewSet
from wagtail.core import hooks as hooks
from wagtail.users.forms import GroupForm as GroupForm, GroupPagePermissionFormSet as GroupPagePermissionFormSet
from wagtail.users.views.users import index as index

def get_permission_panel_classes(): ...

class PermissionPanelFormsMixin:
    def get_permission_panel_form_kwargs(self, cls: Any): ...
    def get_permission_panel_forms(self): ...
    def get_context_data(self, **kwargs: Any): ...

class IndexView(mixins.SearchableListMixin, generic.IndexView):
    page_title: Any = ...
    add_item_label: Any = ...
    search_box_placeholder: Any = ...
    search_fields: Any = ...
    context_object_name: str = ...
    paginate_by: int = ...
    page_kwarg: str = ...
    ordering: Any = ...
    def get_template_names(self): ...

class CreateView(PermissionPanelFormsMixin, generic.CreateView):
    page_title: Any = ...
    success_message: Any = ...
    template_name: str = ...
    object: Any = ...
    def post(self, request: Any, *args: Any, **kwargs: Any): ...
    def get_context_data(self, **kwargs: Any): ...

class EditView(PermissionPanelFormsMixin, generic.EditView):
    success_message: Any = ...
    error_message: Any = ...
    delete_item_label: Any = ...
    context_object_name: str = ...
    template_name: str = ...
    object: Any = ...
    def post(self, request: Any, *args: Any, **kwargs: Any): ...
    def get_context_data(self, **kwargs: Any): ...

class DeleteView(generic.DeleteView):
    success_message: Any = ...
    page_title: Any = ...
    confirmation_message: Any = ...
    template_name: str = ...

class GroupViewSet(ModelViewSet):
    icon: str = ...
    model: Any = ...
    index_view_class: Any = ...
    add_view_class: Any = ...
    edit_view_class: Any = ...
    delete_view_class: Any = ...
    @property
    def users_view(self): ...
    def get_form_class(self, for_update: bool = ...): ...
    def get_urlpatterns(self): ...
