from django.contrib.sitemaps import Sitemap as DjangoSitemap
from typing import Any, Optional

class Sitemap(DjangoSitemap):
    request: Any = ...
    def __init__(self, request: Optional[Any] = ...) -> None: ...
    def location(self, obj: Any): ...
    def lastmod(self, obj: Any): ...
    def get_wagtail_site(self): ...
    def items(self): ...
