from django.db import models
from typing import Any
from wagtail.search.models import Query as Query

class SearchPromotion(models.Model):
    query: Any = ...
    page: Any = ...
    sort_order: Any = ...
    description: Any = ...
    class Meta:
        ordering: Any = ...
        verbose_name: Any = ...
