from typing import Any
from wagtail.admin import messages as messages
from wagtail.admin.auth import any_permission_required as any_permission_required, permission_required as permission_required
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.contrib.search_promotions import forms as forms
from wagtail.search.models import Query as Query

def index(request: Any): ...
def save_searchpicks(query: Any, new_query: Any, searchpicks_formset: Any): ...
def add(request: Any): ...
def edit(request: Any, query_id: Any): ...
def delete(request: Any, query_id: Any): ...
