from typing import Any
from wagtail.admin.menu import MenuItem as MenuItem
from wagtail.contrib.search_promotions import admin_urls as admin_urls
from wagtail.core import hooks as hooks

def register_admin_urls(): ...

class SearchPicksMenuItem(MenuItem):
    def is_shown(self, request: Any): ...

def register_search_picks_menu_item(): ...
def register_permissions(): ...
