from typing import Any
from wagtail.search.backends.elasticsearch2 import ElasticsearchAutocompleteQueryCompilerImpl as ElasticsearchAutocompleteQueryCompilerImpl
from wagtail.search.backends.elasticsearch6 import Elasticsearch6Index as Elasticsearch6Index, Elasticsearch6Mapping as Elasticsearch6Mapping, Elasticsearch6SearchBackend as Elasticsearch6SearchBackend, Elasticsearch6SearchQueryCompiler as Elasticsearch6SearchQueryCompiler, Elasticsearch6SearchResults as Elasticsearch6SearchResults
from wagtail.search.index import class_is_indexed as class_is_indexed

class Elasticsearch7Mapping(Elasticsearch6Mapping):
    def get_mapping(self): ...

class Elasticsearch7Index(Elasticsearch6Index):
    def add_model(self, model: Any) -> None: ...
    def add_item(self, item: Any) -> None: ...
    def add_items(self, model: Any, items: Any) -> None: ...
    def delete_item(self, item: Any) -> None: ...

class Elasticsearch7SearchQueryCompiler(Elasticsearch6SearchQueryCompiler):
    mapping_class: Any = ...

class Elasticsearch7SearchResults(Elasticsearch6SearchResults): ...
class Elasticsearch7AutocompleteQueryCompiler(Elasticsearch6SearchQueryCompiler, ElasticsearchAutocompleteQueryCompilerImpl): ...

class Elasticsearch7SearchBackend(Elasticsearch6SearchBackend):
    mapping_class: Any = ...
    index_class: Any = ...
    query_compiler_class: Any = ...
    autocomplete_query_compiler_class: Any = ...
    results_class: Any = ...
    settings: Any = ...
SearchBackend = Elasticsearch7SearchBackend
