from .elasticsearch2 import Elasticsearch2Index as Elasticsearch2Index, Elasticsearch2Mapping as Elasticsearch2Mapping, Elasticsearch2SearchBackend as Elasticsearch2SearchBackend, Elasticsearch2SearchQueryCompiler as Elasticsearch2SearchQueryCompiler, Elasticsearch2SearchResults as Elasticsearch2SearchResults, ElasticsearchAutocompleteQueryCompilerImpl as ElasticsearchAutocompleteQueryCompilerImpl
from typing import Any

class Elasticsearch5Mapping(Elasticsearch2Mapping):
    keyword_type: str = ...
    text_type: str = ...
    set_index_not_analyzed_on_filter_fields: bool = ...

class Elasticsearch5Index(Elasticsearch2Index): ...

class Elasticsearch5SearchQueryCompiler(Elasticsearch2SearchQueryCompiler):
    mapping_class: Any = ...
    def get_query(self): ...

class Elasticsearch5AutocompleteQueryCompiler(Elasticsearch5SearchQueryCompiler, ElasticsearchAutocompleteQueryCompilerImpl): ...

class Elasticsearch5SearchResults(Elasticsearch2SearchResults):
    fields_param_name: str = ...

class Elasticsearch5SearchBackend(Elasticsearch2SearchBackend):
    mapping_class: Any = ...
    index_class: Any = ...
    query_compiler_class: Any = ...
    autocomplete_query_compiler_class: Any = ...
    results_class: Any = ...
SearchBackend = Elasticsearch5SearchBackend
