from .elasticsearch2 import ElasticsearchAutocompleteQueryCompilerImpl as ElasticsearchAutocompleteQueryCompilerImpl
from .elasticsearch5 import Elasticsearch5Index as Elasticsearch5Index, Elasticsearch5Mapping as Elasticsearch5Mapping, Elasticsearch5SearchBackend as Elasticsearch5SearchBackend, Elasticsearch5SearchQueryCompiler as Elasticsearch5SearchQueryCompiler, Elasticsearch5SearchResults as Elasticsearch5SearchResults
from typing import Any

class Elasticsearch6Mapping(Elasticsearch5Mapping):
    all_field_name: str = ...
    edgengrams_field_name: str = ...
    def get_document_id(self, obj: Any): ...
    def get_document_type(self): ...
    def get_mapping(self): ...

class Elasticsearch6Index(Elasticsearch5Index): ...

class Elasticsearch6SearchQueryCompiler(Elasticsearch5SearchQueryCompiler):
    mapping_class: Any = ...

class Elasticsearch6SearchResults(Elasticsearch5SearchResults): ...
class Elasticsearch6AutocompleteQueryCompiler(Elasticsearch6SearchQueryCompiler, ElasticsearchAutocompleteQueryCompilerImpl): ...

class Elasticsearch6SearchBackend(Elasticsearch5SearchBackend):
    mapping_class: Any = ...
    index_class: Any = ...
    query_compiler_class: Any = ...
    autocomplete_query_compiler_class: Any = ...
    results_class: Any = ...
SearchBackend = Elasticsearch6SearchBackend
