from django.apps import AppConfig
from typing import Any

class WagtailAPIV2AppConfig(AppConfig):
    name: str = ...
    label: str = ...
    verbose_name: Any = ...
    def ready(self) -> None: ...
