from .utils import BadRequestError as BadRequestError
from rest_framework.pagination import BasePagination
from typing import Any, Optional

class WagtailPagination(BasePagination):
    view: Any = ...
    total_count: Any = ...
    def paginate_queryset(self, queryset: Any, request: Any, view: Optional[Any] = ...): ...
    def get_paginated_response(self, data: Any): ...
