from typing import Any
from wagtail.utils.urlpatterns import decorate_urlpatterns as decorate_urlpatterns

class WagtailAPIRouter:
    url_namespace: Any = ...
    def __init__(self, url_namespace: Any) -> None: ...
    def register_endpoint(self, name: Any, class_: Any) -> None: ...
    def get_model_endpoint(self, model: Any): ...
    def get_model_listing_urlpath(self, model: Any): ...
    def get_object_detail_urlpath(self, model: Any, pk: Any): ...
    def wrap_view(self, func: Any): ...
    def get_urlpatterns(self): ...
    @property
    def urls(self): ...
