from typing import Any, Optional
from wagtail.core.models import Page as Page, Site as Site
from wagtail.core.utils import resolve_model_string as resolve_model_string

class BadRequestError(Exception): ...

def get_base_url(request: Optional[Any] = ...): ...
def get_full_url(request: Any, path: Any): ...
def get_object_detail_url(router: Any, request: Any, model: Any, pk: Any): ...
def page_models_from_string(string: Any): ...
def filter_page_type(queryset: Any, page_models: Any): ...

class FieldsParameterParseError(ValueError): ...

def parse_fields_parameter(fields_str: Any): ...
def parse_boolean(value: Any): ...
