from ..models import SourceImageIOError as SourceImageIOError
from rest_framework.fields import Field
from typing import Any

class ImageRenditionField(Field):
    filter_spec: Any = ...
    def __init__(self, filter_spec: Any, *args: Any, **kwargs: Any) -> None: ...
    def to_representation(self, image: Any): ...
