from ... import get_image_model as get_image_model
from .serializers import ImageSerializer as ImageSerializer
from typing import Any
from wagtail.api.v2.filters import FieldsFilter as FieldsFilter, OrderingFilter as OrderingFilter, SearchFilter as SearchFilter
from wagtail.api.v2.views import BaseAPIViewSet as BaseAPIViewSet

class ImagesAPIViewSet(BaseAPIViewSet):
    base_serializer_class: Any = ...
    filter_backends: Any = ...
    body_fields: Any = ...
    meta_fields: Any = ...
    listing_default_fields: Any = ...
    nested_default_fields: Any = ...
    name: str = ...
    model: Any = ...
