from typing import Any
from wagtail.admin.auth import PermissionPolicyChecker as PermissionPolicyChecker
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.admin.modal_workflow import render_modal_workflow as render_modal_workflow
from wagtail.admin.models import popular_tags_for_model as popular_tags_for_model
from wagtail.core import hooks as hooks
from wagtail.core.models import Collection as Collection
from wagtail.images import get_image_model as get_image_model
from wagtail.images.formats import get_image_format as get_image_format
from wagtail.images.forms import ImageInsertionForm as ImageInsertionForm, get_image_form as get_image_form
from wagtail.images.permissions import permission_policy as permission_policy

permission_checker: Any
CHOOSER_PAGE_SIZE: Any

def get_chooser_js_data(): ...
def get_image_result_data(image: Any): ...
def get_chooser_context(request: Any): ...
def chooser(request: Any): ...
def image_chosen(request: Any, image_id: Any): ...
def chooser_upload(request: Any): ...
def chooser_select_format(request: Any, image_id: Any): ...
