from typing import Any
from wagtail.admin import messages as messages
from wagtail.admin.auth import PermissionPolicyChecker as PermissionPolicyChecker
from wagtail.admin.forms.search import SearchForm as SearchForm
from wagtail.admin.models import popular_tags_for_model as popular_tags_for_model
from wagtail.core.models import Collection as Collection, Site as Site
from wagtail.images import get_image_model as get_image_model
from wagtail.images.exceptions import InvalidFilterSpecError as InvalidFilterSpecError
from wagtail.images.forms import URLGeneratorForm as URLGeneratorForm, get_image_form as get_image_form
from wagtail.images.models import Filter as Filter, SourceImageIOError as SourceImageIOError
from wagtail.images.permissions import permission_policy as permission_policy
from wagtail.images.utils import generate_signature as generate_signature

permission_checker: Any
INDEX_PAGE_SIZE: Any
USAGE_PAGE_SIZE: Any

def index(request: Any): ...
def edit(request: Any, image_id: Any): ...
def url_generator(request: Any, image_id: Any): ...
def generate_url(request: Any, image_id: Any, filter_spec: Any): ...
def preview(request: Any, image_id: Any, filter_spec: Any): ...
def delete(request: Any, image_id: Any): ...
def add(request: Any): ...
def usage(request: Any, image_id: Any): ...
