from typing import Any, Optional
from wagtail.admin.auth import PermissionPolicyChecker as PermissionPolicyChecker
from wagtail.images import get_image_model as get_image_model
from wagtail.images.fields import ALLOWED_EXTENSIONS as ALLOWED_EXTENSIONS
from wagtail.images.forms import get_image_form as get_image_form
from wagtail.images.models import UploadedImage as UploadedImage
from wagtail.images.permissions import permission_policy as permission_policy
from wagtail.search.backends import get_search_backends as get_search_backends

permission_checker: Any

def get_image_edit_form(ImageModel: Any): ...
def add(request: Any): ...
def edit(request: Any, image_id: Any, callback: Optional[Any] = ...): ...
def delete(request: Any, image_id: Any): ...
def create_from_uploaded_image(request: Any, uploaded_image_id: Any): ...
def delete_upload(request: Any, uploaded_image_id: Any): ...
