from django.views.generic import View
from typing import Any, Optional
from wagtail.images import get_image_model as get_image_model
from wagtail.images.exceptions import InvalidFilterSpecError as InvalidFilterSpecError
from wagtail.images.models import SourceImageIOError as SourceImageIOError
from wagtail.images.utils import generate_signature as generate_signature, verify_signature as verify_signature
from wagtail.utils.sendfile import sendfile as sendfile

def generate_image_url(image: Any, filter_spec: Any, viewname: str = ..., key: Optional[Any] = ...): ...

class ServeView(View):
    model: Any = ...
    action: str = ...
    key: Any = ...
    def as_view(cls, **initkwargs: Any): ...
    def get(self, request: Any, signature: Any, image_id: Any, filter_spec: Any, filename: Optional[Any] = ...): ...
    def serve(self, rendition: Any): ...
    def redirect(self, rendition: Any): ...

serve: Any

class SendFileView(ServeView):
    backend: Any = ...
    def serve(self, rendition: Any): ...
