from django.forms import MediaDefiningClass
from typing import Any, Optional
from wagtail.core import hooks as hooks
from wagtail.snippets.permissions import get_permission_name as get_permission_name

class ActionMenuItem(metaclass=MediaDefiningClass):
    order: int = ...
    template: str = ...
    label: str = ...
    name: Any = ...
    classname: str = ...
    icon_name: str = ...
    def __init__(self, order: Optional[Any] = ...) -> None: ...
    def is_shown(self, request: Any, context: Any): ...
    def get_context(self, request: Any, parent_context: Any): ...
    def get_url(self, request: Any, context: Any) -> None: ...
    def render_html(self, request: Any, parent_context: Any): ...

class DeleteMenuItem(ActionMenuItem):
    name: str = ...
    label: Any = ...
    icon_name: str = ...
    classname: str = ...
    def is_shown(self, request: Any, context: Any): ...
    def get_url(self, request: Any, context: Any): ...

class SaveMenuItem(ActionMenuItem):
    name: str = ...
    label: Any = ...
    template: str = ...

def get_base_snippet_action_menu_items(model: Any): ...

class SnippetActionMenu:
    template: str = ...
    request: Any = ...
    context: Any = ...
    menu_items: Any = ...
    default_item: Any = ...
    def __init__(self, request: Any, **kwargs: Any): ...
    def render_html(self): ...
    def media(self): ...
