from typing import Any
from wagtail.core.blocks import ChooserBlock as ChooserBlock
from wagtail.core.utils import resolve_model_string as resolve_model_string

class SnippetChooserBlock(ChooserBlock):
    def __init__(self, target_model: Any, **kwargs: Any) -> None: ...
    def target_model(self): ...
    def widget(self): ...
    class Meta:
        icon: str = ...
