from .widgets import AdminSnippetChooser as AdminSnippetChooser
from typing import Any
from wagtail.admin.edit_handlers import BaseChooserPanel as BaseChooserPanel

class SnippetChooserPanel(BaseChooserPanel):
    object_type_name: str = ...
    def widget_overrides(self): ...
    def render_as_field(self): ...
    target_model: Any = ...
    def on_model_bound(self) -> None: ...
