from typing import Any
from wagtail.snippets.models import get_snippet_models as get_snippet_models

def get_permission_name(action: Any, model: Any): ...
def user_can_edit_snippet_type(user: Any, model: Any): ...
def user_can_edit_snippets(user: Any): ...
