from typing import Any
from wagtail.admin.staticfiles import versioned_static as versioned_static
from wagtail.admin.widgets import AdminChooser as AdminChooser
from wagtail.admin.widgets.button import ListingButton as ListingButton

class AdminSnippetChooser(AdminChooser):
    target_model: Any = ...
    choose_one_text: Any = ...
    choose_another_text: Any = ...
    link_to_chosen_text: Any = ...
    def __init__(self, model: Any, **kwargs: Any) -> None: ...
    def render_html(self, name: Any, value: Any, attrs: Any): ...
    def render_js_init(self, id_: Any, name: Any, value: Any): ...
    @property
    def media(self): ...

class SnippetListingButton(ListingButton): ...
