from django.forms import widgets
from typing import Any
from wagtail.admin.edit_handlers import RichTextFieldPanel as RichTextFieldPanel
from wagtail.admin.rich_text.converters.contentstate import ContentstateConverter as ContentstateConverter
from wagtail.admin.staticfiles import versioned_static as versioned_static

class DraftailRichTextArea(widgets.HiddenInput):
    template_name: str = ...
    is_hidden: bool = ...
    accepts_features: bool = ...
    def get_panel(self): ...
    options: Any = ...
    plugins: Any = ...
    features: Any = ...
    converter: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def format_value(self, value: Any): ...
    def get_context(self, name: Any, value: Any, attrs: Any): ...
    def value_from_datadict(self, data: Any, files: Any, name: Any): ...
    def media(self): ...
