from typing import Any, Optional
from wagtail.admin.staticfiles import versioned_static as versioned_static

class Feature:
    js: Any = ...
    css: Any = ...
    def __init__(self, js: Optional[Any] = ..., css: Optional[Any] = ...) -> None: ...
    @property
    def media(self): ...

class BooleanFeature(Feature):
    option_name: Any = ...
    def __init__(self, option_name: Any, **kwargs: Any) -> None: ...
    def construct_options(self, options: Any) -> None: ...

class ListFeature(Feature):
    data: Any = ...
    def __init__(self, data: Any, **kwargs: Any) -> None: ...
    def construct_options(self, options: Any) -> None: ...

class EntityFeature(ListFeature):
    option_name: str = ...

class BlockFeature(ListFeature):
    option_name: str = ...

class InlineStyleFeature(ListFeature):
    option_name: str = ...
