from django.db import models
from typing import Any, Optional
from wagtail.search.utils import MAX_QUERY_STRING_LENGTH as MAX_QUERY_STRING_LENGTH, normalise_query_string as normalise_query_string

class Query(models.Model):
    query_string: Any = ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def add_hit(self, date: Optional[Any] = ...) -> None: ...
    @property
    def hits(self): ...
    @classmethod
    def garbage_collect(cls) -> None: ...
    @classmethod
    def get(cls, query_string: Any): ...
    @classmethod
    def get_most_popular(cls, date_since: Optional[Any] = ...): ...

class QueryDailyHits(models.Model):
    query: Any = ...
    date: Any = ...
    hits: Any = ...
    @classmethod
    def garbage_collect(cls, days: Optional[Any] = ...) -> None: ...
