from typing import Any, Optional
from wagtail.search import index as index

def post_save_signal_handler(instance: Any, update_fields: Optional[Any] = ..., **kwargs: Any) -> None: ...
def post_delete_signal_handler(instance: Any, **kwargs: Any) -> None: ...
def register_signal_handlers() -> None: ...
