from .utils import get_descendants_content_types_pks as get_descendants_content_types_pks
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from typing import Any
from wagtail.search.index import class_is_indexed as class_is_indexed

class TextIDGenericRelation(GenericRelation):
    auto_created: bool = ...
    def get_content_type_lookup(self, alias: Any, remote_alias: Any): ...
    def get_object_id_lookup(self, alias: Any, remote_alias: Any): ...
    def get_extra_restriction(self, where_class: Any, alias: Any, remote_alias: Any): ...
    def resolve_related_fields(self): ...

class IndexEntry(models.Model):
    content_type: Any = ...
    object_id: Any = ...
    content_object: Any = ...
    autocomplete: Any = ...
    title: Any = ...
    title_norm: Any = ...
    body: Any = ...
    @property
    def model(self): ...
    @classmethod
    def add_generic_relations(cls) -> None: ...
