from django import forms
from typing import Any
from wagtail.core.models import Page as Page

class PageChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj: Any): ...

class ParentChooserForm(forms.Form):
    parent_page: Any = ...
    valid_parents_qs: Any = ...
    def __init__(self, valid_parents_qs: Any, *args: Any, **kwargs: Any) -> None: ...
