from .finders import get_finders as get_finders
from django.apps import AppConfig
from typing import Any

class WagtailEmbedsAppConfig(AppConfig):
    name: str = ...
    label: str = ...
    verbose_name: Any = ...
    def ready(self) -> None: ...
