from typing import Any
from wagtail.core import blocks as blocks
from wagtail.embeds.format import embed_to_frontend_html as embed_to_frontend_html

class EmbedValue:
    url: Any = ...
    def __init__(self, url: Any) -> None: ...
    def html(self): ...

class EmbedBlock(blocks.URLBlock):
    def get_default(self): ...
    def to_python(self, value: Any): ...
    def get_prep_value(self, value: Any): ...
    def value_for_form(self, value: Any): ...
    def value_from_form(self, value: Any): ...
    def clean(self, value: Any): ...
    class Meta:
        icon: str = ...
