from django.db import models
from typing import Any

EMBED_TYPES: Any

class Embed(models.Model):
    url: Any = ...
    max_width: Any = ...
    type: Any = ...
    html: Any = ...
    title: Any = ...
    author_name: Any = ...
    provider_name: Any = ...
    thumbnail_url: Any = ...
    width: Any = ...
    height: Any = ...
    last_updated: Any = ...
    class Meta:
        unique_together: Any = ...
        verbose_name: Any = ...
        verbose_name_plural: Any = ...
    @property
    def ratio(self): ...
    @property
    def ratio_css(self): ...
    @property
    def is_responsive(self): ...
