from typing import Any
from urllib.request import Request

logger: Any

class PurgeRequest(Request):
    def get_method(self): ...

class BaseBackend:
    def purge(self, url: Any) -> None: ...
    def purge_batch(self, urls: Any) -> None: ...

class HTTPBackend(BaseBackend):
    cache_scheme: Any = ...
    cache_netloc: Any = ...
    def __init__(self, params: Any) -> None: ...
    def purge(self, url: Any) -> None: ...

class CloudflareBackend(BaseBackend):
    CHUNK_SIZE: int = ...
    cloudflare_email: Any = ...
    cloudflare_api_key: Any = ...
    cloudflare_token: Any = ...
    cloudflare_zoneid: Any = ...
    def __init__(self, params: Any) -> None: ...
    def purge_batch(self, urls: Any) -> None: ...
    def purge(self, url: Any) -> None: ...

class CloudfrontBackend(BaseBackend):
    client: Any = ...
    cloudfront_distribution_id: Any = ...
    def __init__(self, params: Any) -> None: ...
    def purge_batch(self, urls: Any) -> None: ...
    def purge(self, url: Any) -> None: ...
