from typing import Any
from wagtail.contrib.frontend_cache.utils import purge_page_from_cache as purge_page_from_cache
from wagtail.core.signals import page_published as page_published, page_unpublished as page_unpublished

def page_published_signal_handler(instance: Any, **kwargs: Any) -> None: ...
def page_unpublished_signal_handler(instance: Any, **kwargs: Any) -> None: ...
def register_signal_handlers() -> None: ...
