from django.core.exceptions import ImproperlyConfigured
from typing import Any, Optional
from wagtail.core.utils import get_content_languages as get_content_languages

logger: Any

class InvalidFrontendCacheBackendError(ImproperlyConfigured): ...

def get_backends(backend_settings: Optional[Any] = ..., backends: Optional[Any] = ...): ...
def purge_url_from_cache(url: Any, backend_settings: Optional[Any] = ..., backends: Optional[Any] = ...) -> None: ...
def purge_urls_from_cache(urls: Any, backend_settings: Optional[Any] = ..., backends: Optional[Any] = ...) -> None: ...
def purge_page_from_cache(page: Any, backend_settings: Optional[Any] = ..., backends: Optional[Any] = ...) -> None: ...
def purge_pages_from_cache(pages: Any, backend_settings: Optional[Any] = ..., backends: Optional[Any] = ...) -> None: ...

class PurgeBatch:
    urls: Any = ...
    def __init__(self, urls: Optional[Any] = ...) -> None: ...
    def add_url(self, url: Any) -> None: ...
    def add_urls(self, urls: Any) -> None: ...
    def add_page(self, page: Any) -> None: ...
    def add_pages(self, pages: Any) -> None: ...
    def purge(self, backend_settings: Optional[Any] = ..., backends: Optional[Any] = ...) -> None: ...
