from .templatetags.wagtailcore_tags import pageurl as pageurl, richtext as richtext, slugurl as slugurl, wagtail_version as wagtail_version
from jinja2.ext import Extension
from typing import Any

class WagtailCoreExtension(Extension):
    tags: Any = ...
    def __init__(self, environment: Any) -> None: ...
    def parse(self, parser: Any): ...
    def parse_include_block(self, parser: Any): ...
core = WagtailCoreExtension
