from typing import Any, Optional
from wagtail.core.models import Page as Page, Site as Site

logger: Any

def post_save_site_signal_handler(instance: Any, update_fields: Optional[Any] = ..., **kwargs: Any) -> None: ...
def post_delete_site_signal_handler(instance: Any, **kwargs: Any) -> None: ...
def pre_delete_page_unpublish(sender: Any, instance: Any, **kwargs: Any) -> None: ...
def post_delete_page_log_deletion(sender: Any, instance: Any, **kwargs: Any) -> None: ...
def register_signal_handlers() -> None: ...
