from typing import Any, Optional

class RouteResult:
    page: Any = ...
    args: Any = ...
    kwargs: Any = ...
    def __init__(self, page: Any, args: Optional[Any] = ..., kwargs: Optional[Any] = ...) -> None: ...
    def __getitem__(self, index: Any): ...
