from typing import Any, Optional

WAGTAIL_APPEND_SLASH: Any

def camelcase_to_underscore(str: Any): ...
def string_to_ascii(value: Any): ...
def get_model_string(model: Any): ...
def resolve_model_string(model_string: Any, default_app: Optional[Any] = ...): ...

SCRIPT_RE: Any

def escape_script(text: Any): ...

SLUGIFY_RE: Any

def cautious_slugify(value: Any): ...
def safe_snake_case(value: Any): ...
def accepts_kwarg(func: Any, kwarg: Any): ...

class InvokeViaAttributeShortcut:
    obj: Any = ...
    method_name: Any = ...
    def __init__(self, obj: Any, method_name: Any) -> None: ...
    def __getattr__(self, name: Any): ...

def find_available_slug(parent: Any, requested_slug: Any, ignore_page_id: Optional[Any] = ...): ...
def get_content_languages(): ...
def get_supported_content_language_variant(lang_code: Any, strict: bool = ...): ...
def reset_cache(**kwargs: Any) -> None: ...
