from typing import Any

ALLOWED_URL_SCHEMES: Any
PROTOCOL_RE: Any

def check_url(url_string: Any): ...
def attribute_rule(allowed_attrs: Any): ...

allow_without_attributes: Any
DEFAULT_ELEMENT_RULES: Any

class Whitelister:
    element_rules: Any = ...
    def clean(self, html: Any): ...
    def clean_node(self, doc: Any, node: Any) -> None: ...
    def clean_string_node(self, doc: Any, node: Any) -> None: ...
    def clean_tag_node(self, doc: Any, tag: Any) -> None: ...
    def clean_unknown_node(self, doc: Any, node: Any) -> None: ...
