from typing import Any, Optional
from wagtail.core.models import Task as Task

TASK_TYPES: Any

def get_concrete_descendants(model_class: Any, inclusive: bool = ...) -> None: ...
def get_task_types(task_class: Optional[Any] = ...): ...
def publish_workflow_state(workflow_state: Any, user: Optional[Any] = ...) -> None: ...
