from typing import Any, Optional
from wagtail.admin.rich_text.converters.html_to_contentstate import HtmlToContentStateHandler as HtmlToContentStateHandler

def link_entity(props: Any): ...
def br(props: Any): ...
def block_fallback(props: Any) -> None: ...
def entity_fallback(props: Any) -> None: ...

class ContentstateConverter:
    features: Any = ...
    html_to_contentstate_handler: Any = ...
    exporter: Any = ...
    def __init__(self, features: Optional[Any] = ...) -> None: ...
    def from_database_format(self, html: Any): ...
    def to_database_format(self, contentstate_json: Any): ...
