from typing import Any

ALPHANUM: Any

class Block:
    type: Any = ...
    depth: Any = ...
    text: str = ...
    key: Any = ...
    inline_style_ranges: Any = ...
    entity_ranges: Any = ...
    def __init__(self, typ: Any, depth: int = ...) -> None: ...
    def as_dict(self): ...

class InlineStyleRange:
    style: Any = ...
    offset: Any = ...
    length: Any = ...
    def __init__(self, style: Any) -> None: ...
    def as_dict(self): ...

class Entity:
    entity_type: Any = ...
    mutability: Any = ...
    data: Any = ...
    def __init__(self, entity_type: Any, mutability: Any, data: Any) -> None: ...
    def as_dict(self): ...

class EntityRange:
    key: Any = ...
    offset: Any = ...
    length: Any = ...
    def __init__(self, key: Any) -> None: ...
    def as_dict(self): ...

class ContentState:
    blocks: Any = ...
    entity_count: int = ...
    entity_map: Any = ...
    def __init__(self) -> None: ...
    def add_entity(self, entity: Any): ...
    def as_dict(self): ...
    def as_json(self, **kwargs: Any): ...
