from typing import Any, Optional

class ButtonHelper:
    default_button_classnames: Any = ...
    add_button_classnames: Any = ...
    inspect_button_classnames: Any = ...
    edit_button_classnames: Any = ...
    delete_button_classnames: Any = ...
    view: Any = ...
    request: Any = ...
    model: Any = ...
    opts: Any = ...
    verbose_name: Any = ...
    verbose_name_plural: Any = ...
    permission_helper: Any = ...
    url_helper: Any = ...
    def __init__(self, view: Any, request: Any) -> None: ...
    def finalise_classname(self, classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
    def add_button(self, classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
    def inspect_button(self, pk: Any, classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
    def edit_button(self, pk: Any, classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
    def delete_button(self, pk: Any, classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
    def get_buttons_for_obj(self, obj: Any, exclude: Optional[Any] = ..., classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...

class PageButtonHelper(ButtonHelper):
    unpublish_button_classnames: Any = ...
    copy_button_classnames: Any = ...
    def unpublish_button(self, pk: Any, classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
    def copy_button(self, pk: Any, classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
    def get_buttons_for_obj(self, obj: Any, exclude: Optional[Any] = ..., classnames_add: Optional[Any] = ..., classnames_exclude: Optional[Any] = ...): ...
