from typing import Any
from wagtail.core.models import Page as Page, UserPagePermissionsProxy as UserPagePermissionsProxy

class PermissionHelper:
    model: Any = ...
    opts: Any = ...
    inspect_view_enabled: Any = ...
    def __init__(self, model: Any, inspect_view_enabled: bool = ...) -> None: ...
    def get_all_model_permissions(self): ...
    def get_perm_codename(self, action: Any): ...
    def user_has_specific_permission(self, user: Any, perm_codename: Any): ...
    def user_has_any_permissions(self, user: Any): ...
    def user_can_list(self, user: Any): ...
    def user_can_create(self, user: Any): ...
    def user_can_inspect_obj(self, user: Any, obj: Any): ...
    def user_can_edit_obj(self, user: Any, obj: Any): ...
    def user_can_delete_obj(self, user: Any, obj: Any): ...
    def user_can_unpublish_obj(self, user: Any, obj: Any): ...
    def user_can_copy_obj(self, user: Any, obj: Any): ...

class PagePermissionHelper(PermissionHelper):
    def get_valid_parent_pages(self, user: Any): ...
    def user_can_list(self, user: Any): ...
    def user_can_create(self, user: Any): ...
    def user_can_edit_obj(self, user: Any, obj: Any): ...
    def user_can_delete_obj(self, user: Any, obj: Any): ...
    def user_can_publish_obj(self, user: Any, obj: Any): ...
    def user_can_copy_obj(self, user: Any, obj: Any): ...
