from typing import Any, Optional
from wagtail.search.backends import get_search_backend as get_search_backend

class BaseSearchHandler:
    search_fields: Any = ...
    def __init__(self, search_fields: Any) -> None: ...
    def search_queryset(self, queryset: Any, search_term: Any, **kwargs: Any) -> None: ...
    @property
    def show_search_form(self): ...

class DjangoORMSearchHandler(BaseSearchHandler):
    def search_queryset(self, queryset: Any, search_term: Any, **kwargs: Any): ...
    @property
    def show_search_form(self): ...

class WagtailBackendSearchHandler(BaseSearchHandler):
    default_search_backend: str = ...
    def search_queryset(self, queryset: Any, search_term: Any, preserve_order: bool = ..., operator: Optional[Any] = ..., partial_match: bool = ..., backend: Optional[Any] = ..., **kwargs: Any): ...
