from typing import Any

class AdminURLHelper:
    model: Any = ...
    opts: Any = ...
    def __init__(self, model: Any) -> None: ...
    def get_action_url_pattern(self, action: Any): ...
    def get_action_url_name(self, action: Any): ...
    def get_action_url(self, action: Any, *args: Any, **kwargs: Any): ...
    def index_url(self): ...
    def create_url(self): ...

class PageAdminURLHelper(AdminURLHelper):
    def get_action_url(self, action: Any, *args: Any, **kwargs: Any): ...
