from . import checks as checks
from django.apps import AppConfig
from typing import Any

class WagtailImagesAppConfig(AppConfig):
    name: str = ...
    label: str = ...
    verbose_name: Any = ...
    def ready(self) -> None: ...
