from .shortcuts import get_rendition_or_not_found as get_rendition_or_not_found
from typing import Any, Optional
from wagtail.admin.compare import BlockComparison as BlockComparison
from wagtail.core.blocks import ChooserBlock as ChooserBlock

class ImageChooserBlock(ChooserBlock):
    def target_model(self): ...
    def widget(self): ...
    def render_basic(self, value: Any, context: Optional[Any] = ...): ...
    def get_comparison_class(self): ...
    class Meta:
        icon: str = ...

class ImageChooserBlockComparison(BlockComparison):
    def htmlvalue(self, val: Any): ...
    def htmldiff(self): ...
