from .widgets import AdminImageChooser as AdminImageChooser
from wagtail.admin.compare import ForeignObjectComparison as ForeignObjectComparison
from wagtail.admin.edit_handlers import BaseChooserPanel as BaseChooserPanel

class ImageChooserPanel(BaseChooserPanel):
    object_type_name: str = ...
    def widget_overrides(self): ...
    def get_comparison_class(self): ...

class ImageFieldComparison(ForeignObjectComparison):
    def htmldiff(self): ...
