from django import forms
from typing import Any
from wagtail.admin import widgets as widgets
from wagtail.admin.forms.collections import BaseCollectionMemberForm as BaseCollectionMemberForm, CollectionChoiceField as CollectionChoiceField, collection_member_permission_formset_factory as collection_member_permission_formset_factory
from wagtail.core.models import Collection as Collection
from wagtail.images.fields import WagtailImageField as WagtailImageField
from wagtail.images.formats import get_image_formats as get_image_formats
from wagtail.images.models import Image as Image

def formfield_for_dbfield(db_field: Any, **kwargs: Any): ...

class BaseImageForm(BaseCollectionMemberForm):
    permission_policy: Any = ...

def get_image_form(model: Any): ...

class ImageInsertionForm(forms.Form):
    format: Any = ...
    alt_text: Any = ...

class URLGeneratorForm(forms.Form):
    filter_method: Any = ...
    width: Any = ...
    height: Any = ...
    closeness: Any = ...

GroupImagePermissionFormSet: Any
