from .shortcuts import get_rendition_or_not_found as get_rendition_or_not_found
from typing import Any, Optional
from wagtail.utils.apps import get_app_submodules as get_app_submodules

class Format:
    name: Any = ...
    label: Any = ...
    classnames: Any = ...
    filter_spec: Any = ...
    def __init__(self, name: Any, label: Any, classnames: Any, filter_spec: Any) -> None: ...
    def editor_attributes(self, image: Any, alt_text: Any): ...
    def image_to_editor_html(self, image: Any, alt_text: Any): ...
    def image_to_html(self, image: Any, alt_text: Any, extra_attributes: Optional[Any] = ...): ...

FORMATS: Any
FORMATS_BY_NAME: Any

def register_image_format(format: Any) -> None: ...
def unregister_image_format(format_name: Any) -> None: ...
def get_image_formats(): ...
def get_image_format(name: Any): ...
def search_for_image_formats() -> None: ...
