from typing import Any
from wagtail.images.exceptions import InvalidFilterSpecError as InvalidFilterSpecError
from wagtail.images.rect import Rect as Rect
from wagtail.images.utils import parse_color_string as parse_color_string

class Operation:
    method: Any = ...
    args: Any = ...
    def __init__(self, method: Any, *args: Any) -> None: ...
    def construct(self, *args: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any) -> None: ...

class DoNothingOperation(Operation):
    def construct(self) -> None: ...
    def run(self, willow: Any, image: Any, env: Any) -> None: ...

class FillOperation(Operation):
    vary_fields: Any = ...
    width: Any = ...
    height: Any = ...
    crop_closeness: int = ...
    def construct(self, size: Any, *extra: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any): ...

class MinMaxOperation(Operation):
    width: Any = ...
    height: Any = ...
    def construct(self, size: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any): ...

class WidthHeightOperation(Operation):
    size: Any = ...
    def construct(self, size: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any): ...

class ScaleOperation(Operation):
    percent: Any = ...
    def construct(self, percent: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any): ...

class JPEGQualityOperation(Operation):
    quality: Any = ...
    def construct(self, quality: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any) -> None: ...

class WebPQualityOperation(Operation):
    quality: Any = ...
    def construct(self, quality: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any) -> None: ...

class FormatOperation(Operation):
    format: Any = ...
    options: Any = ...
    def construct(self, format: Any, *options: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any) -> None: ...

class BackgroundColorOperation(Operation):
    color: Any = ...
    def construct(self, color_string: Any) -> None: ...
    def run(self, willow: Any, image: Any, env: Any): ...
