from typing import Any
from wagtail.images import get_image_model as get_image_model

def post_delete_file_cleanup(instance: Any, **kwargs: Any): ...
def post_delete_purge_rendition_cache(instance: Any, **kwargs: Any) -> None: ...
def pre_save_image_feature_detection(instance: Any, **kwargs: Any) -> None: ...
def register_signal_handlers() -> None: ...
