from typing import Any, Optional

def get_fill_filter_spec_migrations(app_name: Any, rendition_model_name: Any): ...
def parse_color_string(color_string: Any): ...
def generate_signature(image_id: Any, filter_spec: Any, key: Optional[Any] = ...): ...
def verify_signature(signature: Any, image_id: Any, filter_spec: Any, key: Optional[Any] = ...): ...
