from typing import Any
from wagtail.admin.menu import MenuItem as MenuItem
from wagtail.admin.navigation import get_site_for_user as get_site_for_user
from wagtail.admin.rich_text import HalloPlugin as HalloPlugin
from wagtail.admin.search import SearchArea as SearchArea
from wagtail.admin.site_summary import SummaryItem as SummaryItem
from wagtail.core import hooks as hooks
from wagtail.images import admin_urls as admin_urls, get_image_model as get_image_model, image_operations as image_operations
from wagtail.images.api.admin.views import ImagesAdminAPIViewSet as ImagesAdminAPIViewSet
from wagtail.images.forms import GroupImagePermissionFormSet as GroupImagePermissionFormSet
from wagtail.images.permissions import permission_policy as permission_policy
from wagtail.images.rich_text import ImageEmbedHandler as ImageEmbedHandler
from wagtail.images.rich_text.contentstate import ContentstateImageConversionRule as ContentstateImageConversionRule
from wagtail.images.rich_text.editor_html import EditorHTMLImageConversionRule as EditorHTMLImageConversionRule

def register_admin_urls(): ...
def construct_admin_api(router: Any) -> None: ...

class ImagesMenuItem(MenuItem):
    def is_shown(self, request: Any): ...

def register_images_menu_item(): ...
def editor_js(): ...
def register_image_feature(features: Any) -> None: ...
def register_image_operations(): ...

class ImagesSummaryItem(SummaryItem):
    order: int = ...
    template: str = ...
    def get_context(self): ...
    def is_shown(self): ...

def add_images_summary_item(request: Any, items: Any) -> None: ...

class ImagesSearchArea(SearchArea):
    def is_shown(self, request: Any): ...

def register_images_search_area(): ...
def register_image_permissions_panel(): ...
def describe_collection_docs(collection: Any): ...
