from django.db import models
from typing import Any
from wagtail.admin.models import get_object_usage as get_object_usage
from wagtail.core.models import CollectionMember as CollectionMember
from wagtail.search import index as index
from wagtail.search.queryset import SearchableQuerySetMixin as SearchableQuerySetMixin

class DocumentQuerySet(SearchableQuerySetMixin, models.QuerySet): ...

class AbstractDocument(CollectionMember, index.Indexed, models.Model):
    title: Any = ...
    file: Any = ...
    created_at: Any = ...
    uploaded_by_user: Any = ...
    tags: Any = ...
    file_size: Any = ...
    file_hash: Any = ...
    objects: Any = ...
    search_fields: Any = ...
    def clean(self) -> None: ...
    def is_stored_locally(self): ...
    def open_file(self) -> None: ...
    def get_file_size(self): ...
    def get_file_hash(self): ...
    @property
    def filename(self): ...
    @property
    def file_extension(self): ...
    @property
    def url(self): ...
    def get_usage(self): ...
    @property
    def usage_url(self): ...
    def is_editable_by_user(self, user: Any): ...
    @property
    def content_type(self): ...
    @property
    def content_disposition(self): ...
    class Meta:
        abstract: bool = ...
        verbose_name: Any = ...
        verbose_name_plural: Any = ...

class Document(AbstractDocument):
    admin_form_fields: Any = ...

document_served: Any
