from typing import Any
from wagtail.documents import get_document_model as get_document_model

def post_delete_file_cleanup(instance: Any, **kwargs: Any): ...
def register_signal_handlers() -> None: ...
